server:
  port: 9091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

client:
  ms-product:
    endpoint: localhost:9090